apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

# Enlazamos el parche indicándole a Kustomize el objetivo exacto para evitar el error noNs
patches:
  - target:
      kind: Deployment
      name: chatbot-backend
    path: patches-resilience.yaml
