apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
spec:
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          # Blanda/Preferencial: Habilita la simulación elástica multi-réplica en un solo nodo local
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - chatbot-backend
              topologyKey: "kubernetes.io/hostname"
