FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY gateway-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la API de Alertas Interactivas
COPY gateway-api/src/app.py .

# INJECCIÓN DEL BIARIO CON IA: Copiar el Fat JAR compilado físicamente en tu Mac
COPY spark-runtime/target/scala-2.12/spark-runtime-assembly-3.5.0.jar ./spark-runtime/target/scala-2.12/

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
