FROM docker.io/library/nginx:alpine

# Copiar todos tus archivos estáticos al directorio por defecto de Nginx de forma explícita
COPY src/index.html src/app.js src/style.css /usr/share/nginx/html/
COPY src/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
