[pytest]
log_cli = true
log_cli_level = DEBUG
log_cli_format = %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# Forzar el renderizado de colores ANSI y fijar el scope asíncrono estándar
addopts = --color=yes -p no:warnings
asyncio_default_fixture_loop_scope = function
