# ======================================================================================================================
# GOBERNANZA CENTRAL DE COMPILACIÓN DE LA JVM - OMEGA QUALITY MESH
# ======================================================================================================================
# @param sbt.version
# Forzar versión unificada para mitigar conflictos de mutación entre Akka gRPC, Flink y Spark Runtimes.
sbt.version=1.9.7
