akka {
  loglevel = "INFO"
  http.server.preview.enable-http2 = true
}

server {
  interface = "0.0.0.0"
  port = 8082
}

pulsar {
  broker-url = "pulsar://pulsar-standalone-broker.ai-deequ.svc.cluster.local:6650"
  topic-name = "persistent://public/default/chat-messages-raw"
}
