# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import inference_pb2 as protos_dot_inference__pb2


class InferenceEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessInference = channel.unary_unary(
                '/inference.InferenceEngine/ProcessInference',
                request_serializer=protos_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=protos_dot_inference__pb2.InferenceResponse.FromString,
                )


class InferenceEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessInference': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessInference,
                    request_deserializer=protos_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=protos_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.InferenceEngine/ProcessInference',
            protos_dot_inference__pb2.InferenceRequest.SerializeToString,
            protos_dot_inference__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
