# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/chatbot.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'src/chatbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11src/chatbot.proto\x12\x07\x63hatbot\"G\n\x0b\x43hatRequest\x12\x13\n\x0braw_message\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"o\n\x0c\x43hatResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\t\x12\x15\n\rchunk_message\x18\x03 \x01(\t\x12\x13\n\x0bis_finished\x18\x04 \x01(\x08\x12\x12\n\ncreated_at\x18\x05 \x01(\t2X\n\x0e\x43hatbotService\x12\x46\n\x15ProcesarMensajeStream\x12\x14.chatbot.ChatRequest\x1a\x15.chatbot.ChatResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.chatbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=30
  _globals['_CHATREQUEST']._serialized_end=101
  _globals['_CHATRESPONSE']._serialized_start=103
  _globals['_CHATRESPONSE']._serialized_end=214
  _globals['_CHATBOTSERVICE']._serialized_start=216
  _globals['_CHATBOTSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
