flink {
  # Paralelismo por defecto para no saturar los hilos de CPU en Colima
  default-parallelism = 1
  
  # Intervalo de checkpoints para la tolerancia a fallas Exactly-Once
  checkpoint-interval-ms = 10000
}

pulsar {
  # 🚀 CONECTOR CORREGIDO PARA KUBERNETES:
  broker-url = "pulsar://pulsar-standalone-broker.ai-deequ.svc.cluster.local:6650"
  admin-url = "http://cluster.local"
  subscription-name = "flink-chat-ingest-sub-v4"
  topic-chat = "persistent://public/default/chat-messages-raw"
  max-fetch-records = 500
}

ai-service {
  api-url = "http://cluster.local"
  timeout-ms = 30000
  max-concurrent-requests = 5
  max-retries = 3
  retry-backoff-ms = 1000
}