apiVersion: v1
kind: Service
metadata:
  name: ai-deequ-flink-jobmanager
  namespace: ai-deequ
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: ui
    port: 8081
  selector:
    app: ai-deequ-flink
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deequ-flink-jobmanager
  namespace: ai-deequ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-deequ-flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: ai-deequ-flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.18.1
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 8081
          name: ui
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: ai-deequ-flink-jobmanager
            blob.server.port: 6124
            jobmanager.memory.process.size: 1600m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deequ-flink-taskmanager
  namespace: ai-deequ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-deequ-flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: ai-deequ-flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.18.1
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: data
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: ai-deequ-flink-jobmanager
            taskmanager.numberOfTaskSlots: 2
            taskmanager.memory.process.size: 1728m
