# ==============================================================================
# 🪐 CONFIGURACIÓN PERIMETRAL DEL GATEWAY DE AKKA HTTP (PRODUCCIÓN HÍBRIDA)
# ==============================================================================

akka {
  # Nivel de auditoría interno para el pool de actores y sockets de red
  loglevel = "INFO"
  
  # 🚀 PROPIEDAD HISTÓRICA CONSERVADA: Habilita el soporte multiplexado de HTTP/2
  http.server.preview.enable-http2 = true
}

server {
  # Interfaz elástica y puerto de escucha enlazados al balanceador de Kubernetes
  interface = "0.0.0.0"
  port = 8082
}

pulsar {
  # 🚀 DNS CANÓNICO COMPLETO: Resuelve la ruta sin colisiones dentro del namespace ai-deequ
  broker-url = "pulsar://pulsar-standalone-broker.ai-deequ.svc.cluster.local:6650"
  
  # Tópico compartido de ingesta analítica en abanico (Fan-Out Pattern)
  topic-name = "persistent://public/default/chat-messages-raw"
}
