apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 🪐 COMPONENTES LOCALES: Los tres pilares reales que viven físicamente en esta carpeta base
resources:
  - infrastructure.yaml
  - deployment.yaml
  - gateway-nativo.yaml
