# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"H\n\rTelemetryData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x14\n\x0cmetric_value\x18\x02 \x01(\x01\x12\x0e\n\x06region\x18\x03 \x01(\t\"\xed\x01\n\x10InferenceRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x15\n\rstep_sequence\x18\x02 \x01(\x05\x12\x15\n\rprevious_hash\x18\x03 \x01(\t\x12+\n\ttelemetry\x18\x04 \x01(\x0b\x32\x18.inference.TelemetryData\x12;\n\x08metadata\x18\x05 \x03(\x0b\x32).inference.InferenceRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"T\n\x11InferenceResponse\x12\x11\n\tledger_id\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x01\x12\x12\n\nis_anomaly\x18\x03 \x01(\x08\x32`\n\x0fInferenceEngine\x12M\n\x10ProcessInference\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERENCEREQUEST_METADATAENTRY']._options = None
  _globals['_INFERENCEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYDATA']._serialized_start=30
  _globals['_TELEMETRYDATA']._serialized_end=102
  _globals['_INFERENCEREQUEST']._serialized_start=105
  _globals['_INFERENCEREQUEST']._serialized_end=342
  _globals['_INFERENCEREQUEST_METADATAENTRY']._serialized_start=295
  _globals['_INFERENCEREQUEST_METADATAENTRY']._serialized_end=342
  _globals['_INFERENCERESPONSE']._serialized_start=344
  _globals['_INFERENCERESPONSE']._serialized_end=428
  _globals['_INFERENCEENGINE']._serialized_start=430
  _globals['_INFERENCEENGINE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
