server {
    listen 80;
    server_name localhost;
    server_tokens off;

    location / {
        root /usr/share/nginx/html/nexus-frontend;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 🚀 ENRUTE INTERNO DE ALTO RENDIMIENTO HACIA TU FASTAPI
    location /api/chat/stream {
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        # 🧠 EL CAMBIO: Enviamos la petición HTTP limpia al Service de FastAPI (8501)
        # para que él se encargue de hablar con el backend por gRPC
        set $upstream_target http://cluster.local;
        proxy_pass $upstream_target;

        # Desactivamos el buffering para garantizar Streaming Puro en tu script
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache off;
        proxy_buffering off;
        chunked_transfer_encoding on;
        proxy_read_timeout 3600s;
    }
}
