apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-ai-engine.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # Las cadenas viajan cifradas en Base64 por el pipeline. Aquí mapeamos la variable del values
  noSqlConnectionString: {{ .Values.secrets.noSqlConnectionString | b64enc | quote }}
