apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-ai-engine.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: grpc-port
    name: grpc
    protocol: TCP
  selector:
    {{- include "helm-ai-engine.selectorLabels" . | nindent 4 }}
